'''
Created on 2016-04-29

Copyright (c) 2016 Bradford Dillman

@author: bdillman

xform which generates code from models and templates.
'''

import logging

from fashion import templates

logging.debug("gen loaded")

def inputKinds():
    '''Inputs consumed by this xform'''
    return [ 'fashion_gen' ]

def outputKinds():
    '''Outputs generated by this xform'''
    return [ ]


def police(fashion_gen):
    '''Validate models before xform.'''
    pass

def xform(fashion_gen):
    '''Perform source generation from template.'''
    logging.debug("gen xform running")
    for f in fashion_gen:
        m = f.loadFile()
        templates.generateFile(**m)
